### ISSUE TITLE
Status is not a dcd command

### ISSUE THREAD

**Issue by HugoGresse** [devicecloud-dev/device-cloud-for-maestro#18]
Hi,

Using DeviceCloud action today resulted in: 

```
Run devicecloud-dev/device-cloud-for-maestro@v1
  with:
    api-key: ***
    app-file: exported_artefacts/PlantNet.app
    workspace: e2e/
    env: API_URL=https://h.app/
  
 ›   Warning: 
 ›   -------------------
 ›   A new version of the devicecloud.dev CLI is available: 3.3.5
 ›   Run 'npm install -g @devicecloud.dev/dcd@latest' to update to the latest 
 ›   version
 ›   -------------------
 ›
 ›   Warning: status is not a dcd command.
 ›   Error: Run dcd help for a list of available commands.
Failed to get test status: Error: Command failed: npx --yes @devicecloud.dev/dcd status --json --upload-id axxxxxxxxxx770563 --api-key *** --api-url https://api.devicecloud.dev/
 ›   Warning: status is not a dcd command.
 ›   Error: Run dcd help for a list of available commands.

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at /builds/actions-runner/_work/_actions/devicecloud-dev/device-cloud-for-maestro/v1/dist/index.js:32583:59
    at Generator.next (<anonymous>)
    at /builds/actions-runner/_work/_actions/devicecloud-dev/device-cloud-for-maestro/v1/dist/index.js:32566:71
    at new Promise (<anonymous>)
    at __webpack_modules__.6144.__awaiter (/builds/actions-runner/_work/_actions/devicecloud-dev/device-cloud-for-maestro/v1/dist/index.js:32562:12)
    at getTestStatus (/builds/actions-runner/_work/_actions/devicecloud-dev/device-cloud-for-maestro/v1/dist/index.js:32577:53) {
  status: 127,
  signal: null,
  output: [
    null,
    ' \x1B[0mDid you mean \x1B[94mcloud\x1B[39m?\x1B[0m \x1B[2m(Y/n)\x1B[22m\x1B[28G\n\x1B[?25h',
    ' ›   Warning: \x1B[33mstatus\x1B[39m is not a dcd command.\n' +
      ' ›   Error: Run \x1B[36m\x1B[1mdcd help\x1B[22m\x1B[39m for a list of available commands.\n'
  ],
  pid: 1759565,
  stdout: ' \x1B[0mDid you mean \x1B[94mcloud\x1B[39m?\x1B[0m \x1B[2m(Y/n)\x1B[22m\x1B[28G\n\x1B[?25h',
  stderr: ' ›   Warning: \x1B[33mstatus\x1B[39m is not a dcd command.\n' +
    ' ›   Error: Run \x1B[36m\x1B[1mdcd help\x1B[22m\x1B[39m for a list of available commands.\n'
}
Error: Failed to get test status
```

Action is 
```
            - uses: devicecloud-dev/device-cloud-for-maestro@v1
              id: e2e_tests
              continue-on-error: true
              with:
                  api-key: ${{ secrets.DEVICE_CLOUD_API_KEY }}
                  app-file: exported_artefacts/PlantNet.app
                  workspace: e2e/
                  env: |
                      API_URL=https://h.app

```
